[신우주] ADD:Models 완료
wecode-bootcamp-korea/24-1st-DotFriends-backend pull request #1
Opened 2021-08-31 11:24 UTC by shinwooju

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
dotfriends modeling 완료
		 
## 수정 사항들 자세한 내용

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-31 12:26 UTC, lordmyshepherd requested changes

2021-08-31 12:26 UTC, lordmyshepherd commented on orders/models.py
> +    price    = models.IntegerField()
price는 상품의 total price인가요? 
이미 Product가 price를 가지고 있기 때문에, order_items 테이블에는 불필요할 것 같습니다!

2021-08-31 12:26 UTC, lordmyshepherd commented on orders/models.py
> +
빈 줄은 지워주세요~

2021-08-31 12:26 UTC, lordmyshepherd commented on products/models.py
> +    price            = models.IntegerField()
데이터베이스는 글로벌하게 관리해야 되기 때문에, price는 `DecimalField`를 사용해서 구현해주세요.

2021-08-31 12:26 UTC, lordmyshepherd commented on products/models.py
> +    product = models.ForeignKey('product',on_delete=models.CASCADE)
class명은 카멜케이스로 만들어주세요~
```suggestion
class UserProductLike(models.Model):
    user    = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey('product',on_delete=models.CASCADE)
```

2021-08-31 12:26 UTC, lordmyshepherd commented on orders/models.py
> +        db_table = 'orders'
대부분의 테이블에 이력 관리를 위해서 `created_at`, `updated_at` column을 추가해주세요!!

2021-08-31 12:37 UTC, shinwooju commented on orders/models.py
> +    price    = models.IntegerField()
넵 price 삭제했습니다!

2021-08-31 12:37 UTC, shinwooju commented on orders/models.py
> +
불필요한 공백 삭제했습니다~!

2021-08-31 12:38 UTC, shinwooju commented on products/models.py
> +    price            = models.IntegerField()
DecimalField 사용해서 수정했습니다

2021-08-31 12:38 UTC, shinwooju commented on products/models.py
> +    product = models.ForeignKey('product',on_delete=models.CASCADE)
카멜케이스에 맞춰서 수정하였습니다!

2021-08-31 12:40 UTC, shinwooju commented on orders/models.py
> +        db_table = 'orders'
Order
OrderItem
Product
User 에 해당 컬럼 추가했습니다.

2021-09-01 01:34 UTC, lordmyshepherd commented
LGTM 👍

2021-09-01 01:34 UTC, merged