[서동규]Udate: 상품상세페이지 view 수정
wecode-bootcamp-korea/24-1st-DotFriends-backend pull request #12
Opened 2021-09-07 13:49 UTC by sdk1926

## 수정 사항 간략한 한줄 요약
- 로그인 한 사용자가 상세페이지를 조회할 경우를 추가 
		 
## 수정 사항들 자세한 내용
- visitor_validator 데코레이터로 로그인한 사용자와 로그인 하지 않은 사용자를 식별한 후 
해당 상품이 로그인한 유저가 찜하기를 누른 상품이면 결과값에 좋아요 여부에 true를 반환
- 로그인을 했지만 좋아요를 누르지 않았거나 로그인하지 않은 경우 좋아요 여부에 false를 반환
- 로그인 한 사용자일 경우 쿼리호출이 2번 추가됨 
- 로그인을 하지 않으면 기존과 돌일하게 쿼리는 3번 호출 

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-07 15:16 UTC, lordmyshepherd requested changes

2021-09-07 15:16 UTC, lordmyshepherd commented on products/views.py
> +    @visitor_validator
사용 목적이 궁굼합니다!

2021-09-07 15:16 UTC, lordmyshepherd commented on products/views.py
> +        print(likes)
프린트문은 지워주세요~

2021-09-07 23:26 UTC, sdk1926 commented on products/views.py
> +    @visitor_validator
상품 상세 페이지를 보면 로그인 한 유저가 자신이 찜하기를 눌렀던 상품은 빨간색 하트로 표시가 됩니다. 
찜하기를 누르지 않았더라면 표시가 되지 않습니다. 
@visitor_validator를 사용하는 이유는 해당상품이 로그인한 유져가 좋아요를 눌렀던 상품인지 아닌지를 식별하기 위해서 로그인한 유저의 정보를 체크 합니다. 
request.header에 authorization이 없으면 바로 ProductDetailView를 실행하고 토큰이 있으면 해석해서 유저의 정보를 request.user에 담아서 ProductDetailView를 실행합니다. 
그리고 유저의 아이디를 가지고 해당상품에 좋아요를 눌렀는지 안눌렀는지 여부를 확인해서 results값에 좋아요 여부를 넣어줍니다.

2021-09-07 23:28 UTC, sdk1926 commented on products/views.py
> +    @visitor_validator
<img width="385" alt="스크린샷 2021-09-08 오전 8 27 35" src="https://user-images.githubusercontent.com/67228062/132422878-b36b9688-58d1-424c-9801-e5376875db41.png">
<img width="398" alt="스크린샷 2021-09-08 오전 8 27 21" src="https://user-images.githubusercontent.com/67228062/132422896-56495477-d5b5-4dfa-be07-0c8d42f334c2.png">

2021-09-07 23:29 UTC, sdk1926 commented on products/views.py
> +        print(likes)
반영했습니다.

2021-09-07 23:35 UTC, sdk1926 commented on products/views.py
> +    @visitor_validator
프론트엔드에서 참 거짓 여부를 갖고 페이지를 그려줄 때 하트가 빨간색일지 아닐지를 결정해서 그려줍니다.

2021-09-08 09:55 UTC, lordmyshepherd requested changes

2021-09-08 09:55 UTC, lordmyshepherd commented on products/views.py
> +                likes = 'Yes'
동규님! `line 96~99` 부분을 아래 코드에 합칠 수 있는 방법을 고민해보시면 좋을 것 같아요!

말씀드린 것 처럼 `nested if` 과연 최선인가?!

힌트 (`Case When`)

```python
product  = Product.objects.annotate(avg_rate=Avg('comment__rate'),likes=Count("userproductlike", distinct=True)\
            ,comment_count=Count('comment',distinct=True)).get(id=product_id)
```

2021-09-09 01:54 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-09 02:15 UTC, merged