[신우주] ADD:users.views.py sign_up/sign_in
wecode-bootcamp-korea/24-1st-DotFriends-backend pull request #2
Opened 2021-09-01 06:46 UTC by shinwooju

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
views.py signup/signin 추가 
		 
## 수정 사항들 자세한 내용
requirements.txt = bcrypt추가, pyjwt추가
users.views.py 
signup추가
- 정규표현식 사용 및 비밀번호 암호화
signin추가
- 로그인 성공시 토큰발행

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-01 08:39 UTC, lordmyshepherd requested changes

2021-09-01 08:39 UTC, lordmyshepherd commented on users/views.py
> +from my_settings import SECRET_KEY
`my_settings.py`가 아니라 django settings.py에서 불러와서 사용하도록 수정해주세요~

```suggestion
from my_settings import SECRET_KEY
```

2021-09-01 08:39 UTC, lordmyshepherd commented on users/views.py
> +            Valid_email    = re.compile('^[a-zA-Z\d+-_.]+@[a-zA-Z\d]+\.[a-zA-Z\d+-.]+$')
정규식은 아래와 같이 `regex`라는 용어를 많이 붙여서 사용합니다.

```suggestion
            REGEX_EMAIL = re.compile('^[a-zA-Z\d+-_.]+@[a-zA-Z\d]+\.[a-zA-Z\d+-.]+$')
            REGEX_PASSWORD = re.compile('^(?=.*[a-zA-Z])(?=.*[\d])(?=.*[~!@#$%^&*_+])[a-zA-Z\d~!@#$%^&*_+]{8,}$')
```

2021-09-01 08:39 UTC, lordmyshepherd commented on users/views.py
> +            ck_password    = data['ck_password']
`ck_password`는 어떤 비밀번호인가요?

2021-09-01 08:39 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
`User.objects.get(email=data['email'])` method를 호출할 때마다, database에 요청이 발생하게 됩니다.
그런데 지금 코드는 get() 호출을 두번이나 하고 있습니다. (line 65, line 66)

중복을 제거해주시고, database 요청도 한번으로 줄여주세요~

2021-09-01 10:13 UTC, shinwooju commented on users/views.py
> +from my_settings import SECRET_KEY
from django.conf import settings 로 바꾸고 
74번째줄 토큰 생성시 시크릿키 settings에서 불러와서 생성할 수 있도록 수정했습니다.

2021-09-01 10:13 UTC, shinwooju commented on users/views.py
> +            Valid_email    = re.compile('^[a-zA-Z\d+-_.]+@[a-zA-Z\d]+\.[a-zA-Z\d+-.]+$')
regex로 수정완료했습니다.

2021-09-01 10:14 UTC, shinwooju commented on users/views.py
> +            ck_password    = data['ck_password']
ck_password 에서 다른팀원들이 봐도 쉽게이해할수 있게 check_password로 수정했습니다.

2021-09-01 10:14 UTC, shinwooju commented on users/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
변수를 지정해서 수정했습니다.

2021-09-02 01:35 UTC, lordmyshepherd requested changes

2021-09-02 01:35 UTC, lordmyshepherd commented on users/views.py
> +                    return JsonResponse({'MESSAGE':'SUCCESS', 'TOKEN' : token}, status=200)
nested if문은 최대한 줄여서 사용하는게 좋습니다.
nested if문을 사용하게되면 분기처리가 많아진다는 얘기로 디버깅하기가 어렵습니다! 최대한 선형적으로 로직을 작성하도록 해주세요~

```suggestion
            if not User.objects.filter(email=email).exists():
                return JsonResponse({'MESSAGE':'USER_DOES_NOT_EXIST'}, status=401)
            
            user = User.objects.get(email=email)
            
            if not bcrypt.checkpw(data['password'].encode('utf-8'), user.password.encode('utf-8')):
                return JsonResponse({'MESSAGE':'INVALID_USER'}, status=401)
            
            token = jwt.encode({'id' : user.id}, settings.SECRET_KEY, algorithm='HS256')
            
            return JsonResponse({'MESSAGE':'SUCCESS', 'TOKEN' : token}, status=200)
```

2021-09-02 02:14 UTC, shinwooju commented on users/views.py
> +                    return JsonResponse({'MESSAGE':'SUCCESS', 'TOKEN' : token}, status=200)
감사합니다 로직 수정했습니다

2021-09-02 04:53 UTC, lordmyshepherd commented
LGTM 👍

2021-09-02 04:54 UTC, merged