Add: 메인페이지 슬라이더 뷰 구현
wecode-bootcamp-korea/24-1st-DotFriends-backend pull request #3
Opened 2021-09-01 07:28 UTC by sdk1926

## 수정 사항 간략한 한줄 요약
- 메인페이지 슬라이더 뷰 기능 구현
 		 
## 수정 사항들 자세한 내용
-get으로 요청해서 쿼리파라미터 값을 안주거나 쿼리파라미터에 지정한값이 아니면 WRONG_ACCESS 메세지를 주고 400에러를 반환합니다.
-option쿼리 파라미터의 값이 new면 Product모델의 신상이 True인 항목을 랜덤으로 정렬해서 12개를 뽑아서 전달해 줍니다.
-option쿼리 파라미터의 값이 sale이면 Product모델의 할인율이 0이 아닌 항목을 랜덤으로 정렬해서 12개를 뽑아서 전달해 줍니다.

## 기타 질문 및 특이 사항
- 쿼리파라미터 값을 안주거나 쿼리파라미터에 지정한값이 아니면 WRONG_ACCESS 메세지를 주고 400에러를 반환하게 했습니다.
왜냐하면 제가 지정한 url포맷이 아니기 때문에 잘못된 요청이라는 메세지와 400에러를 반환했는데 이렇게 하는 것이 맞는지 궁금합니다!
- 좀 더 효율적인 방법이 궁금합니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-01 08:54 UTC, lordmyshepherd requested changes

2021-09-01 08:54 UTC, lordmyshepherd commented on products/views.py
> +class MainPageView(View):
"MainPage에 필요한 데이터를 반환해야 된다."라는 생각 때문에 `MainPageView` 라는 class명을 사용하신 것 같습니다.
API는 페이지를 기준으로 만드시면 안됩니다. API는 자원(data)를 기준으로 작성해주셔야 합니다. 즉, 엔드포인트는 페이지에 의존성을 갖도록 만들면 안되고 메인 페이지 뿐만 아니라, 다른 페이지에서도 상품 데이터가 필요하면 아래와 같이 요청해서 받아갈 수 있도록 만들어주셔야 합니다.

```
GET :8000/products -> 상품 리스트를 받아오는 구나!!
GET :8000/product -> 상품을 받아오는 구나!!
```

`Restful API` 개념을 찾아보세요~

2021-09-01 08:54 UTC, lordmyshepherd commented on products/views.py
> +        products = Product.objects.filter(q).order_by("?")[:12]
12개만 받아오도록 구현하신 이유가 있나요?

목록을 반환하는 엔드포인트에 `offset`, `limit` query parameter를 추가해서 유연하게 원하는 만큼의 값을 꺼내올 수 있도록 구현해주세요~

2021-09-01 08:58 UTC, sdk1926 commented on products/views.py
> +class MainPageView(View):
예 알겠습니다!

2021-09-01 08:59 UTC, sdk1926 commented on products/views.py
> +        products = Product.objects.filter(q).order_by("?")[:12]
프론트엔드에서 12개만 필요하다고 해서 지정했습니다. 
병민님 말대로 확작성을 생각해서 원하는 만큼 가져올 수 있도록 수정해보겠습니다.

2021-09-02 01:50 UTC, lordmyshepherd requested changes

2021-09-02 01:50 UTC, lordmyshepherd commented on products/views.py
> +class ProductOptionView(View):
마지막에 반환하는 데이터를 보면 `Product` 리스트를 반환하고 있습니다. 그렇기 때문에 class명도 `ProductListView` 또는 `ProductsView`로 수정해주세요~

```suggestion
class ProductsView(View):
```

2021-09-02 01:50 UTC, lordmyshepherd commented on products/views.py
> +        limit  = request.GET.get('limit', 12)
`offset`, `limit` 잘 적용해주셨네요~ 👍👍👍 
```suggestion
        offset = int(request.GET.get('offset', 1))
        limit  = int(request.GET.get('limit', 12))
```

2021-09-02 01:50 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({'MESSAGE': 'WRONG_ACCESS'}, status=400)
line 22~23은 불필요한 코드 같아 보입니다. `new`와 `option` keword가 없는 경우는 필터링되지 않은 상품 목록을 반환할 수 있어야 되기 때문입니다.
```suggestion
```

2021-09-02 01:50 UTC, lordmyshepherd commented on products/views.py
> +        offset, limit = int(offset), int(limit)
여기도 불필요해 보입니다.

이유는 다음과 같습니다.

1. 가독성이 좋지 않다. 코드의 효율 만큼이나 중요하게 생각하셔야 되는게 가독성입니다. 나와 협업하는 동료들이 코드를 빠르게 파악할 수 있어야되고, 내가 한달 후에 다시 이 코드를 봤을 때, 쉽게 파악할 수 있어야 합니다.

2. line 13~14에서 곧바로 integer로 변환서 변수에 할당해주면 됩니다.

```suggestion

```

2021-09-02 01:50 UTC, lordmyshepherd commented on products/views.py
> +        order  = request.GET.get('order', None)
order를 받을 때 front에서 아래와 같이 받고 default를 "id"로 설정해 놓으면 line 16~ 20까지 코드가 필요 없어 보입니다.

```suggestion

        ?ordering=?
        ?ordering=-id
        ?ordering=id
        
        order  = request.GET.get('order', "id")
```

2021-09-02 02:06 UTC, sdk1926 commented on products/views.py
> +        offset, limit = int(offset), int(limit)
숫자 값으로만 보내면 바로 변환을 해도 되지만 
혹여나 문자열로 보내면 인트형으로 바꿔주면 에러가 나서 미리 문자열인진 아닌지 판단하고 바꿔주었습니다.

2021-09-02 02:07 UTC, sdk1926 commented on products/views.py
> +        order  = request.GET.get('order', None)
이것도 역시 정해진 값으로 보내지 않을 경우를 생각해서 처리했습니다.

2021-09-02 02:12 UTC, sdk1926 commented on products/views.py
> +class ProductOptionView(View):
네 알겠습니다!

2021-09-02 02:12 UTC, sdk1926 commented on products/views.py
> +        limit  = request.GET.get('limit', 12)
감사합니다!

2021-09-02 02:12 UTC, sdk1926 commented on products/views.py
> +            return JsonResponse({'MESSAGE': 'WRONG_ACCESS'}, status=400)
알겠습니다!

2021-09-03 01:40 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-03 04:06 UTC, merged