[서동규]Add: 상품상세페이지 API 구현
wecode-bootcamp-korea/24-1st-DotFriends-backend pull request #8
Opened 2021-09-06 00:44 UTC by sdk1926

## 수정 사항 간략한 한줄 요약
- 상세페이지 조회 API 구현 
		 
## 수정 사항들 자세한 내용
- path파라미터로 상품pk를 받아서 조회 후 있으면 데이터 반환 없으면 404에러 반환 
- 리뷰 데이터도 포함해서 반환 

## 기타 질문 및 특이 사항
- 상품에 딸린 리뷰도 함께 보내주는데 이 부분은 리뷰 조회뷰로 나눠 주는게 좋을지 궁금합니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-06 01:33 UTC, lordmyshepherd requested changes

2021-09-06 01:33 UTC, lordmyshepherd commented on products/decorator.py
> +            limit  = int(request.GET.get('limit', 0))
offset, limt 값이 없으면 default로 10개~20개 정도 반환하도록 만들어주셔야 합니다.
그렇지 않으면 `/products`로 요청한 경우 아무런 값이 반한되지 않겠죠?

2021-09-06 01:33 UTC, lordmyshepherd commented on products/views.py
> +            }for comment in product.comment_set.all()]
Align 맞춰주세요~ 그리고 반환하는 데이터의 계층 구조를 명확하게 만들어주세요!


```suggestion
        results = {
            'id'   : product.id,
            'name' : product.name,
            'review' : [{
                "user_name" : comment.user.name,
                "rate"   : int(comment.rate),
                "text": comment.text
                ]
            ...
            }
```

2021-09-06 02:08 UTC, sdk1926 commented on products/decorator.py
> +            limit  = int(request.GET.get('limit', 0))
병민님 이거는 데코레이터여서 검사만 해서 0으로 했습니다. 
상품리스트 뷰에서 기본값을 설정해도 될까요?

2021-09-06 02:32 UTC, sdk1926 commented on products/views.py
> +            }for comment in product.comment_set.all()]
반영했습니다.

2021-09-07 01:11 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-07 01:11 UTC, lordmyshepherd commented on products/decorator.py
> +            limit  = int(request.GET.get('limit', 0))
아 ㅎㅎ decorator군요!!
네네 상품리스트 뷰에서 설정해주세요~

2021-09-07 01:28 UTC, merged